steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/court-siva-nikhil/meetingbot/web:latest",
        "-f",
        "Dockerfile.web",
        ".",
      ]
images:
  - "asia-south1-docker.pkg.dev/court-siva-nikhil/meetingbot/web:latest"